---
- hosts: kube-master[0]
  roles:
    - { role: roles/postinstall/master }

- hosts: nfs-node
  roles:
    - { role: roles/postinstall/nodes}

- hosts: kube-node
  roles:
    - { role: roles/postinstall/all}