---

- name: copy admin acount chart
  template:
    src: charts/admin-account.yaml.j2
    dest: /home/savi/admin-account.yaml
    owner: root
    group: root
    mode: 0644

- name: copy role binding chart
  template:
    src: charts/role-binding.yaml.j2
    dest: /home/savi/role-binding.yaml
    owner: root
    group: root
    mode: 0644

- name: OpenShift Python Setup
  pip:
    name: openshift

- name: create admin account
  block:
    - k8s:
        state: present
        src: /home/savi/role-binding.yaml

    - k8s:
        state: present
        src: /home/savi/admin-account.yaml

- name: create shared dir
  block:
    - file:
        path: /nfs
        state: directory
        mode: 0777

    - file:
        path: /nfs/root
        state: directory
        mode: 0777

    - file:
        path: /nfs/shared
        state: directory
        mode: 0777

- name: Install nfs server
  apt:
    name: nfs-kernel-server
    update_cache: yes
  when: nfs_server

- name: copy nfs server config file
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  when: nfs_server

- name: restart nfs-server
  service:
    name: nfs-kernel-server
    state: restarted
  when: nfs_server