---

- name: Docker login
  raw:
    docker login -u saeedare -p *****

- name: docker pull image
  raw:
    docker pull hadib/neptunipe:0.1.14

- name: multicast root
  raw:
    route add -net 239.0.0.0/8 cni0